name: numu
description: "numu growth focused habit tracking app"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # routing
  go_router: ^16.3.0

  # state management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # UI packages
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.4+1

  # database
  sqflite: ^2.4.2
  path: ^1.9.1

  # settings storage
  shared_preferences: ^2.3.3

  # reminders and notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  permission_handler: ^11.0.0
  flutter_logs: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # linting
  flutter_lints: ^5.0.0

  # code generation
  build_runner: ^2.4.4
  riverpod_generator: ^3.0.3

  # testing
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true

  # assets:
